#define CYW_STATISTICS_VALID ( \
    NDIS_STATISTICS_FLAGS_VALID_DIRECTED_FRAMES_RCV | \
    NDIS_STATISTICS_FLAGS_VALID_MULTICAST_FRAMES_RCV | \
    NDIS_STATISTICS_FLAGS_VALID_BROADCAST_FRAMES_RCV | \
    NDIS_STATISTICS_FLAGS_VALID_BYTES_RCV | \
    NDIS_STATISTICS_FLAGS_VALID_RCV_DISCARDS | \
    NDIS_STATISTICS_FLAGS_VALID_RCV_ERROR | \
    NDIS_STATISTICS_FLAGS_VALID_DIRECTED_FRAMES_XMIT | \
    NDIS_STATISTICS_FLAGS_VALID_MULTICAST_FRAMES_XMIT | \
    NDIS_STATISTICS_FLAGS_VALID_BROADCAST_FRAMES_XMIT | \
    NDIS_STATISTICS_FLAGS_VALID_BYTES_XMIT | \
    NDIS_STATISTICS_FLAGS_VALID_XMIT_ERROR | \
    NDIS_STATISTICS_FLAGS_VALID_XMIT_DISCARDS | \
    NDIS_STATISTICS_FLAGS_VALID_DIRECTED_BYTES_RCV | \
    NDIS_STATISTICS_FLAGS_VALID_MULTICAST_BYTES_RCV | \
    NDIS_STATISTICS_FLAGS_VALID_BROADCAST_BYTES_RCV | \
    NDIS_STATISTICS_FLAGS_VALID_DIRECTED_BYTES_XMIT | \
    NDIS_STATISTICS_FLAGS_VALID_MULTICAST_BYTES_XMIT | \
    NDIS_STATISTICS_FLAGS_VALID_BROADCAST_BYTES_XMIT )
#define CYW_STATISTICS_SUPPORTED ( \
    NDIS_STATISTICS_DIRECTED_FRAMES_RCV_SUPPORTED | \
    NDIS_STATISTICS_MULTICAST_FRAMES_RCV_SUPPORTED | \
    NDIS_STATISTICS_BROADCAST_FRAMES_RCV_SUPPORTED | \
    NDIS_STATISTICS_BYTES_RCV_SUPPORTED | \
    NDIS_STATISTICS_RCV_DISCARDS_SUPPORTED | \
    NDIS_STATISTICS_RCV_ERROR_SUPPORTED | \
    NDIS_STATISTICS_DIRECTED_FRAMES_XMIT_SUPPORTED | \
    NDIS_STATISTICS_MULTICAST_FRAMES_XMIT_SUPPORTED | \
    NDIS_STATISTICS_BROADCAST_FRAMES_XMIT_SUPPORTED | \
    NDIS_STATISTICS_BYTES_XMIT_SUPPORTED | \
    NDIS_STATISTICS_XMIT_ERROR_SUPPORTED | \
    NDIS_STATISTICS_XMIT_DISCARDS_SUPPORTED | \
    NDIS_STATISTICS_DIRECTED_BYTES_RCV_SUPPORTED | \
    NDIS_STATISTICS_MULTICAST_BYTES_RCV_SUPPORTED | \
    NDIS_STATISTICS_BROADCAST_BYTES_RCV_SUPPORTED | \
    NDIS_STATISTICS_DIRECTED_BYTES_XMIT_SUPPORTED | \
    NDIS_STATISTICS_MULTICAST_BYTES_XMIT_SUPPORTED | \
    NDIS_STATISTICS_BROADCAST_BYTES_XMIT_SUPPORTED )
